const { isUser } = require("../services");
const config = require("../config/env")
const jwt = require("jsonwebtoken")

 
const checkUser = async (req, res, next) => {
  try {
    const { email } = req.body;
    const [user] = await isUser(email);
    if (user) {
      return res.status(400).json({
        status: "failed",
        message: "User already exist",
      });
    }
    next();
  } catch (error) {
    console.log(error.message);
  }
};

const authenticateToken = (req, res, next) => {
  const token = req.body.token || req.query.token || req.headers['x-access-token'];
  // decode the token generated by user payload during signin or signup
  if (token) {
    jwt.verify(token, config.SECRET_KEY, (err, decoded) => {
      if (err) {
        res.status(401);
        res.json({
          status: 'Failed',
          message: 'Authentication failed. Token is either invalid or expired'
        });
      } else {
        req.decoded = decoded;
        next();
      }
    });
  } else {
    res.status(403);
    res.json({
      status: 'Failed',
      message: 'wrong token. provide  a valid token'
    });
  }
};

module.exports = {
  checkUser,
  authenticateToken 
  
};
