const { isUser, Users, signIn } = require("../services");
const config = require("../config/env")
const jwt = require("jsonwebtoken")


const checkUser = async (req, res, next) => {
  try {
    const { email } = req.body;
    const [user] = await isUser(email);
    if (user) {
      return res.status(400).json({
        status: "failed",
        message: "User already exist",
      });
    }
    next();
  } catch (error) {
    console.log(error.message);
  }
};

const authenticateToken = (req, res, next) => {
  const token = req.body.token || req.query.token || req.headers['x-access-token'];
  // decode the token generated by user payload during signin or signup
  if (token) {
    jwt.verify(token, config.SECRET_KEY, (err, decoded) => {
      if (err) {
        res.status(401);
        res.json({
          status: 'Failed',
          message: 'Authentication failed. Token is either invalid or expired'
        });
      } else {
        req.decoded = decoded;
        next();
      }
    });
  } else {
    res.status(403);
    res.json({
      status: 'Failed',
      message: 'wrong token. provide  a valid token'
    });
  }
};

const authenticateIsAdmin = async (req, res, next) => {
  try {
    const userIsAdmin = req.decoded.is_admin;
    if(!userIsAdmin){
      res.json({
        status: "failed",
        message: "user is not an admin"
      }).status(403)
    }
    next();
  } catch (error) {
    console.log(error.message);
  }
} 

const allUsers = (req, res, next) => {
  try {
    const users = Users();
    req.body.isFirstUser = users.length === 0;
    next();
  } catch (error) {
    console.log(error.message)
  }
}


const validateUser = (data, type) => async (req, res, next) => {
  try {
    const getType = {
      body: req.body,
      params: req.params,
      queries: req.queries,
      headers: req.headers,
    };
    const options = {
      language: {
        key: "{{key}}"
      },
    };
    const result = getType[type];
    const isValid = await data.schema.validate(result, options);
    if (!isValid.error) {
      return next();
    }
    const {
      message
    } = isValid.error.details[0];
    return res.status(400).json({
      status: "fail",
      message: message.replace(/[\"]/gi, ""),
      errors: data.message,
    });
  } catch (error) {
    next(error.message);
  }
};

module.exports = {
  checkUser,
  authenticateToken,
  authenticateIsAdmin,
  allUsers,
  validateUser
};
